// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Xe8MOwkB7MaJVZEIE2g2hGo_zVL7tgg',
    appId: '1:300980377611:web:4d35a4d0472d1de5250f0e',
    messagingSenderId: '300980377611',
    projectId: 'nova-cart-71e0a',
    authDomain: 'nova-cart-71e0a.firebaseapp.com',
    storageBucket: 'nova-cart-71e0a.firebasestorage.app',
    measurementId: 'G-Y5E1KVP5DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKCT4fOMzXJtKswzAQIs1lFZk6lKACoYA',
    appId: '1:300980377611:android:b7ad2d288ed5f0d0250f0e',
    messagingSenderId: '300980377611',
    projectId: 'nova-cart-71e0a',
    storageBucket: 'nova-cart-71e0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu7eZy-W6M4-fO31oQz_Nl-jV7YbDjNeo',
    appId: '1:300980377611:ios:5c5e9e1998b050ff250f0e',
    messagingSenderId: '300980377611',
    projectId: 'nova-cart-71e0a',
    storageBucket: 'nova-cart-71e0a.firebasestorage.app',
    iosBundleId: 'com.example.novaCart',
  );
}
